color0 #10141a
color1 #ffb4ab
color2 #aac8f7
color3 #e3badb
color4 #bacf79
color5 #aac8f7
color6 #e3badb
color7 #e0e2eb
color8 #8a919f
color9 #ffb4ab
color10 #aac8f7
color11 #e3badb
color12 #bacf79
color13 #aac8f7
color14 #e3badb
color15 #e0e2eb

cursor                #e0e2eb
cursor_text_color     #10141a
background            #10141a
foreground            #e0e2eb
selection_foreground  #c0c7d5
selection_background  #404753
url_color             #bacf79