# set the terminal emulator to use

set -g default-shell /bin/zsh

# place in ~/.tmux.conf

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

set -g base-index 1
set-option -g status-position top

# Setting up plugin manager
# https://github.com/tmux/tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# tmux-resurrect config
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum config
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Configuring theme
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`
set -g @plugin 'dracula/tmux'
set -g @dracula-colors "
foreground='#ffffff'
background='#002451'
highlight='#003f8e'
status_line='#00346e'
comment='#7285b7'
red='#ff9da4'
orange='#ffc58f'
yellow='#ffeead'
green='#d1f1a9'
aqua='#99ffff'
blue='#bbdaff'
purple='#ebbbff'
pane='#4d5057'
"
set -g @dracula-show-empty-plugins false
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true
set -g @dracula-show-left-icon "tmux"
set -g @dracula-plugins "git cwd ssh-session"
set -g @dracula-git-show-current-symbol 
set -g @dracula-git-show-diff-symbol 
set -g @dracula-git-show-remote-status false
set -g @dracula-show-ssh-only-when-connected true
set -g @dracula-left-icon-colors "blue dark_gray"
set -g @dracula-git-colors "blue dark_gray"
set -g @dracula-cwd-colors "dark_purple white"
set -g @dracula-ssh-session-colors "cyan dark_gray"
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false
run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# For keeping my bg transparent
set -g default-terminal "tmux-256color"
set -g window-style bg=default
set -g status-style bg=default
set -g pane-border-style "fg=colour240,bg=default"
set -g pane-active-border-style "fg=colour51,bg=default"

set -g status-right ""


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

